version: '3.7'
services:
    php:
        restart: 'always'
        image: chrisb9/php8:cli-dev
        environment:
          XDEBUG_MODE: 'coverage'
        volumes:
            - .:/app

    composer:
        restart: 'no'
        image: composer:latest
        command: sh -c "ssh-keyscan -H gitlab.skyts.io >> ~/.ssh/known_hosts && composer update && composer install"
        volumes:
            - .:/app
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      